kind: Pod
apiVersion: v1
metadata:
  name: multi-containers
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1050"]
  - name: nginx
    image: nginx
  - name: nginx
    image: nginx
    